### ISSUE TITLE
Skip the checking of methods of owner and pointer types

### ISSUE THREAD

**Issue by Xazax-hun** [mgehre/clang#30]

**Comment by mgehre** [comment]
I skipped Owners methods in a893693c9e7b6f99eb7fab6002b9874ded574fc7. Not Pointers because the paper says
"We do not currently attempt to check of the internals of Owner types, including that we do not attempt to validate the correctness of pointer-based data structures. Each Owner type is assumed to be correctly implemented, and we check the common uses which greatly outnumber the Owner’s own functions. In this version, implementations are expected to skip analysis member functions of Owner types."
