### ISSUE TITLE
Default constructed std::array causes false positives

### ISSUE THREAD

**Issue by abigailbunyan** [mgehre/clang#45]
The following code:

```cpp
#include <array>

void f() {
    std::array<char, 1> data;
    data[0] = '\0';
}
```

Generates the following false positive `-Wlifetime` warning:
```
<source>:6:5: warning: passing a null pointer as argument to a non-null parameter [-Wlifetime-null]
    data[0] = '\0';
    ^

<source>:5:25: note: default-constructed Pointers are assumed to be null
    std::array<char, 1> data;
                        ^
1 warning generated.
```

I don't think it's correct to consider `std::array` a Pointer at all, but at the very least the assumption about nullness is incorrect.

**Comment by mgehre** [comment]
Thank you for reporting this issue! We will look into this and let you know.

**Comment by Xazax-hun** [comment]
Thanks, great catch! Since std::array does not have a user provided destructor the automatic categorization though that it was a Pointer type. It should be fixed in https://github.com/mgehre/clang/commit/fb055c93260e4793bb71121cf3b6f8e4f20aaf51 . I do not know how often godbolt is updated but the fixes should eventually be pushed there as well.
