### ISSUE TITLE
Support optional DerefType parameter in [[gsl::Owner(DerefType)]] and [[gsl::Pointer(DerefType)]]

### ISSUE THREAD

**Issue by mgehre** [mgehre/clang#8]

**Comment by Xazax-hun** [comment]
I wonder if the parameter should be optional or not. If we want to be convenient and assume that we always have a deref type, we either have to make this non-optional, or failing to recognize the dereftype should result in a compiler error while parsing the attribute.

**Comment by mgehre** [comment]
For users, convenience it should be optional (like the papers says). And yes, good idea, we should diagnose if we cannot determine the deref type. If we do the diagnostics it in Sema while parsing attributes, we would not have to do it in `classifyTypeCategory`.

**Comment by Xazax-hun** [comment]
I think it is ok to the the classification in this check rather than in sema. There might be tons of template instantiations in metaprograms that are never actually used. It would be too bad to attempt to classify them as well. All we need to do is to look up the derefType when we see gsl::Pointer or gsl::Owner annotations rather than doing full classification each time we see a type.

**Comment by Xazax-hun** [comment]
Oh, sorry, I misunderstood you. I agree, determining the DerefType while parsing the attribute is the way to go. But we still need to calculate the DerefType in `classifyTypeCategory` for unannotated types.

**Comment by mgehre** [comment]
Agreed

Gábor Horváth <notifications@github.com> schrieb am Do., 13. Sep. 2018 um
20:34 Uhr:
